data = [
    {"name": "Cristiano Ronaldo", "follower_count": 647, "description": "A Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 504, "description": "A Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 423, "description": "A Singer and Actress", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 395, "description": "A Businesswoman", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 394, "description": "An Actor", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 376, "description": "A Singer", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 359, "description": "A Businesswoman", "country": "USA"},
    {"name": "Beyoncé", "follower_count": 313, "description": "A Singer", "country": "USA"},
    {"name": "Khloé Kardashian", "follower_count": 305, "description": "A Businesswoman", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 295, "description": "A Singer", "country": "Canada"},
    {"name": "Zendaya", "follower_count": 180, "description": "An Actress", "country": "USA"},
    {"name": "Taylor Swift", "follower_count": 235, "description": "A Singer", "country": "USA"},
    {"name": "Jennifer Lopez", "follower_count": 250, "description": "A Singer and Actress", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 265, "description": "A Cricketer", "country": "India"},
    {"name": "Kendall Jenner", "follower_count": 280, "description": "A Model", "country": "USA"},
    {"name": "Cardi B", "follower_count": 220, "description": "A Rapper", "country": "USA"},
    {"name": "Nicki Minaj", "follower_count": 215, "description": "A Rapper", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 200, "description": "A Singer", "country": "USA"},
    {"name": "Chris Hemsworth", "follower_count": 190, "description": "An Actor", "country": "Australia"},
    {"name": "Shakira", "follower_count": 205, "description": "A Singer", "country": "Colombia"},
    {"name": "Will Smith", "follower_count": 180, "description": "An Actor", "country": "USA"},
    {"name": "LeBron James", "follower_count": 175, "description": "A Basketball Player", "country": "USA"},
    {"name": "Billie Eilish", "follower_count": 160, "description": "A Singer", "country": "USA"},
    {"name": "Emma Watson", "follower_count": 145, "description": "An Actress", "country": "UK"},
    {"name": "Shawn Mendes", "follower_count": 155, "description": "A Singer", "country": "Canada"},
    {"name": "Rihanna", "follower_count": 185, "description": "A Singer and Entrepreneur", "country": "Barbados"},
    {"name": "David Beckham", "follower_count": 175, "description": "A Footballer", "country": "UK"},
    {"name": "Gal Gadot", "follower_count": 160, "description": "An Actress", "country": "Israel"},
    {"name": "Priyanka Chopra", "follower_count": 150, "description": "An Actress", "country": "India"},
    {"name": "Zayn Malik", "follower_count": 140, "description": "A Singer", "country": "UK"},
    {"name": "Tom Holland", "follower_count": 170, "description": "An Actor", "country": "UK"},
    {"name": "Drake", "follower_count": 165, "description": "A Rapper", "country": "Canada"},
    {"name": "Camila Cabello", "follower_count": 145, "description": "A Singer", "country": "USA"},
    {"name": "The Weeknd", "follower_count": 150, "description": "A Singer", "country": "Canada"},
    {"name": "Jason Derulo", "follower_count": 140, "description": "A Singer", "country": "USA"},
    {"name": "Ed Sheeran", "follower_count": 180, "description": "A Singer", "country": "UK"},
    {"name": "Christina Aguilera", "follower_count": 130, "description": "A Singer", "country": "USA"},
    {"name": "Kourtney Kardashian", "follower_count": 145, "description": "A Businesswoman", "country": "USA"},
    {"name": "Gigi Hadid", "follower_count": 155, "description": "A Model", "country": "USA"},
    {"name": "Bella Hadid", "follower_count": 150, "description": "A Model", "country": "USA"},
    {"name": "Hugh Jackman", "follower_count": 140, "description": "An Actor", "country": "Australia"},
    {"name": "Demi Lovato", "follower_count": 135, "description": "A Singer", "country": "USA"},
    {"name": "Louis Tomlinson", "follower_count": 130, "description": "A Singer", "country": "UK"},
    {"name": "Ashton Kutcher", "follower_count": 125, "description": "An Actor", "country": "USA"},
    {"name": "Alia Bhatt", "follower_count": 120, "description": "An Actress", "country": "India"},
    {"name": "Deepika Padukone", "follower_count": 140, "description": "An Actress", "country": "India"},
    {"name": "Ranveer Singh", "follower_count": 125, "description": "An Actor", "country": "India"},
    {"name": "Chris Evans", "follower_count": 150, "description": "An Actor", "country": "USA"},
    {"name": "Margot Robbie", "follower_count": 145, "description": "An Actress", "country": "Australia"},
    {"name": "Anushka Sharma", "follower_count": 130, "description": "An Actress", "country": "India"}
]

